# Created by coolzoom Nov 4th 2021 for raspberry pi CI simulation
name: OregonCore Arm(Raspbian Buster for raspberry pi)

on:
  push:
    paths-ignore:
      - 'sql/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'sql/**'
      - 'README.md'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    #git checkout
    - uses: actions/checkout@v2
    # map the source to home folder
    - name: docker setup
      run: |
        docker pull hannseman/raspbian:latest
        docker run -itd --name orpi -p 8085:8085 -p 3306:3306 -p 3724:3724 -v ${{github.workspace}}:/home hannseman/raspbian:latest
        docker exec orpi sh -c 'apt-get update'
    - name: install deps
      run: |
        docker exec orpi sh -c 'apt install g++ cmake git libace-dev libtbb-dev libmariadb-dev libmariadbclient-dev default-libmysqlclient-dev binutils-dev libiberty-dev libncurses-dev libbz2-dev openssl libssl-dev -y'
        docker exec orpi sh -c 'whereis g++'

    - name: cmake
      run: |
        docker exec orpi sh -c 'ls'
        docker exec orpi sh -c 'mkdir -p /home/build'
        docker exec orpi sh -c 'mkdir -p /home/_install'
        docker exec orpi sh -c 'cd /home/build'
        docker exec orpi sh -c 'cmake /home -DCMAKE_INSTALL_PREFIX=/home/_install -DWITH_WARNINGS=0 -DELUNA=1 -DTOOLS=1'
    - name: make and install
      run: |
        docker exec orpi sh -c 'make -j8'
        docker exec orpi sh -c 'make install'
